embedding_size: 300
sentence_size: 100
hidden_size: 150
num_layers: 1
checkpoint_dir: checkpoints
embedding_model: cc.en.300.bin
model_name: microsoft/deberta-v3-base
data_dir: data
data_len: 205000
file_name: sentiment_data.csv
ip: "127.0.0.1"
port: 10000